plugins:
  - '@trivago/prettier-plugin-sort-imports'
arrowParens: avoid
bracketSpacing: true
printWidth: 100
semi: false
singleQuote: true
trailingComma: 'es5'

overrides:
  - files: '*.(ts|mts|tsx)'
    options:
      importOrder:
        - 'node:.+'
        - '<THIRD_PARTY_MODULES>'
        - '<TS_TYPES>'
        - '^[.~](?!.*\.(json)$)'
        - '^[.~].+$'
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      importOrderGroupNamespaceSpecifiers: true
      parser: 'typescript'

  - files: '*.(js|mjs)'
    options:
      importOrder:
        - 'node:.+'
        - '<THIRD_PARTY_MODULES>'
        - '^[.~](?!.*\.(json)$)'
        - '^[.~].+$'
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      importOrderGroupNamespaceSpecifiers: true
      parser: 'babel'
